# Generated by Django 3.2.5 on 2021-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Lorem Ipsum'),
            preserve_default=False,
        ),
    ]
